### ISSUE TITLE
Tasks, Projects und Tags dürfen nur mit id erstellt werden

### ISSUE THREAD

**Issue by carstenhag** [NiklasPor/ToDo#6]
Geht momentan ohne, deswegen kann es zu üblen Zuständen kommen.

**Comment by jzeyer** [comment]
Sollte mit https://github.com/NiklasPor/ToDo/commit/41fa7f732d8d904e438bb628d9c3971898da0f16 behoben sein?

**Comment by carstenhag** [comment]
Warum das Fragezeichen? :D

**Comment by jzeyer** [comment]
> Warum das Fragezeichen? :D

Weil ich noch andere Bestätigungen brauche um es zu schließen 😉
